### ISSUE TITLE
Icons in overview and dash low quality

### ISSUE THREAD

**Issue by TheCultLeader666** [b1izzard-34/Skeuo-icon-theme#1] opened 2021-06-08 18:13 UTC
The icons are pretty low quality when seen in the app grid and the dash, as shown below:
![image](https://user-images.githubusercontent.com/65368815/121236191-ad50c000-c863-11eb-864c-59d317b2424b.png)

**Comment by b1izzard-34** [comment] 2021-06-10 18:11
This is a real bugger !! I am trying to figure it out but don't have any luck in removing this. There is not good documentation about the icon themes and the ones I have read haven't led me to get rid of this. If you find anything regarding this then lemme know :)

**Comment by awcrotwell** [comment] 2021-06-10 18:29
If you look at other icon themes, you can see some differences. I don't know icons so I am just stating what I see. Papirus has some `@2x` folders. like `16x16@2x`. Adwaita has a `scalable` folder using svgs. Both might be worth looking into. 🤷🏼‍♀️

**Comment by b1izzard-34** [comment] 2021-06-14 04:05
@TheCultLeader666 I think the issue is fixed now after I added the scalable icons. Check it out and lemme know

**Closed** 2021-06-14 14:49 UTC
