### ISSUE TITLE
List of Icons that seem reasonably needed (common apps)

### ISSUE THREAD

**Issue by TheCultLeader666** [b1izzard-34/Skeuo-icon-theme#5] opened 2021-06-08 18:38 UTC
Since there are a lot of icons that I think would be reasonable to include, I decided to make a list:

- [x] Gnome Web
- [x] Element
- [x] Firefox Beta
- [x] Firefox Nightly
- [x] Transmission
- [x] VirtualBox
- [x] Zoom
- [x] Screenshot
- [x] Books
- [x] Weather
- [x] Contacts
- [ ] System Monitor
- [x] Lutris
- [ ] Code
- [ ] Notes
- [x] VLC
- [x] Cheese
- [x] Disk Usage Analyzer
- [x] Disks
- [ ] Logs
- [ ] Fonts
- [ ] Help
- [ ] AppImageLauncher
- [ ] Music
- [x] Image Viewer
- [ ] Pidgin
- [ ] Fractal
- [ ] Tor Browser
- [ ] Edge Beta (and presumably other unstable builds, too lazy to look them up)
- [ ] JetBrains IDEs

... and probably others

**Comment by b1izzard-34** [comment] 2021-06-09 03:04
Thanks a lot for the list !! I will keep working on them :)

**Comment by maydayv7** [comment] 2021-06-18 08:49
Please add alacarte, dconf-editor, celluloid and document scanner

**Comment by b1izzard-34** [comment] 2021-06-18 08:52
Please include the icon names with the request. I am not using any of these apps and it's hard to find the names of icon files as it is not same all the time.

**Comment by b1izzard-34** [comment] 2021-06-18 12:37
>     * [ ]  Dconf Editor (dconf-editor and ca.desrt.dconf-editor)
> 
>     * [ ]  Celluloid (io.github.Celluloid and io.github.celluloid_player.Celluloid)
> 
>     * [ ]  Main Menu (alacarte)
> 
>     * [ ]  Document Scanner (org.gnome.SimpleScan)
> 
> 
> EDIT: Sorry for not including previously

no need for sorry haha ... it just makes it a bit convenient :)

**Comment by b1izzard-34** [comment] 2021-06-18 12:46
Duplicate of #15 

Merging all the icon requests in one place for convenience 
Please comment on the issue #15 with the icon names of the apps you use so it would be easy to add them to the icon pack :)

**Closed by b1izzard-34** 2021-06-18 12:46 UTC
