### ISSUE TITLE
[icon request]

### ISSUE THREAD

**Issue by CleoMenezes** [b1izzard-34/Skeuo-icon-theme#10] opened 2021-06-08 23:30 UTC
- 1Password
- WhatsApp
- Spotify
- Visual Studio Code
- NVIDIA X-Server Settings
- Geforce Now
-OBS Studio
- Glades
- Bottles
- RiseupVPN
- Irium webcam
- Simplescreen Recorder
- Figma Linux
- Pamac-manager
- Glimpse
-Gimp

Great job!

**Comment by TheCultLeader666** [comment] 2021-06-08 23:51
Spotify is already in the pack, maybe you missed it?

**Comment by CleoMenezes** [comment] 2021-06-08 23:53
Spotify and discord are missed, bro.
![image](https://user-images.githubusercontent.com/54215258/121272083-169bf780-c893-11eb-800d-0de3b5188996.png)

**Comment by TheCultLeader666** [comment] 2021-06-08 23:59
Not having any problem with SPotify:
![image](https://user-images.githubusercontent.com/65368815/121272450-020c2f00-c894-11eb-87f8-d7d4927aaf98.png)

**Comment by makerio90** [comment] 2021-06-09 13:04
@CleoMenezes 

if those apps were installed via the snap store, there icons wont work. snap apps have hard coded icon paths.

**Comment by b1izzard-34** [comment] 2021-06-10 17:53
@makerio90 this happens because the names of the icon files for the snap store apps is different. So can you find the name of the default spotify icon file of your app and let me know the name of it so I can update it in the theme?

**Comment by makerio90** [comment] 2021-06-10 18:04
> @makerio90 this happens because the names of the icon files for the snap store apps is different. So can you find the name of the default spotify icon file of your app and let me know the name of it so I can update it in the theme?

no, snap apps have hard coded icon paths and won't be affected by icon themes. you can find ware the icon is and replace it manually, but no icon themes are able to override the icons of a snap app

**Comment by b1izzard-34** [comment] 2021-06-10 18:33
I see. Well thanks for the tip. I will add it in the disclaimer then !

**Comment by CleoMenezes** [comment] 2021-06-11 01:19
Guys, it's Flatpak package.

**Comment by makerio90** [comment] 2021-06-12 14:49
@CleoMenezes 
i assume Flatpak has a simmler issue.

**Comment by TheCultLeader666** [comment] 2021-06-12 15:43
@makerio90 no, flatpaks have more standard icons, which can be themed.

**Comment by b1izzard-34** [comment] 2021-06-18 12:45
Duplicate of #15 

Please comment on the issue #15 with the icon names of the apps you use so it would be easy to add them to the icon pack :)

**Closed by b1izzard-34** 2021-06-18 12:45 UTC
