### ISSUE TITLE
List of Icons (less important because these apps are less common)

### ISSUE THREAD

**Issue by TheCultLeader666** [b1izzard-34/Skeuo-icon-theme#11] opened 2021-06-08 23:55 UTC
- [ ] Mullvad VPN
- [ ] Tootle
- [ ] Signal
- [ ] Freetube
- [ ] GDLauncher
- [ ] osu!lazer
- [ ] Spot
- [ ] Mixxx
- [ ] Lunar Client
- [ ] Protonmail Bridge

**Comment by b1izzard-34** [comment] 2021-06-18 12:44
Duplicate of #15 

Please comment on the issue #15 with the icon names of the apps you use so it would be easy to add them to the icon pack :)

**Closed by b1izzard-34** 2021-06-18 12:44 UTC
