### ISSUE TITLE
[Icon request] A list of some icon came to my mind.

### ISSUE THREAD

**Issue by mkblast** [b1izzard-34/Skeuo-icon-theme#9] opened 2021-06-08 22:01 UTC
### Terminals

- [ ] Alacritty
- [ ] Kitty
- [ ] Konsole
- [ ] Xfce Terminal

### Editors

- [ ] Emacs
- [ ] Geany
- [ ] Mousepad
- [x] Gedit
- [ ] Leafpad
- [ ] Vscode / Vscodium
- [ ] Atom
- [ ] Jetbrains IDEs

### File managers

- [ ] Nemo
- [ ] Thunar
- [ ] Dolphin
- [ ] A good PcManFm icon

### Browsers

- [x] Brave
- [ ] Chromium
- [ ] Librewolf
- [ ] Vivaldi
- [ ] Qutebrowser
- [x] GnomeWeb

I hope I helped just a little bit.

**Comment by b1izzard-34** [comment] 2021-06-14 14:48
thanks for the suggestions !! sorry I am replying late. but can you convert your icon list into a tasks list so I can keep track of which ones I have done.

**Comment by mkblast** [comment] 2021-06-18 11:20
> thanks for the suggestions !! sorry I am replying late. but can you convert your icon list into a tasks list so I can keep track of which ones I have done.

too late to replay but DONE!

**Comment by b1izzard-34** [comment] 2021-06-18 12:19
lol it's fine .. thanks for the edit ... also if you are using any of these apps then can you also add the names of the icons as I don't know where to get names of the applications the easy way.

**Comment by b1izzard-34** [comment] 2021-06-18 12:43
Duplicate of #15 

Merging all icon requests in one bundle. Please comment there with the icon names of the applications you use so it would be easy to add them to the icon pack :)

**Closed by b1izzard-34** 2021-06-18 12:43 UTC
